# Generated by Django 5.2.17 on 2026-10-01 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('path', models.TextField(blank=True)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sensitive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retry', 'Retry'), ('sent', 'SMTP accepted'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='hearteli_email_due')],
            },
        ),
    ]
