# Generated by Django 5.2.17 on 2026-10-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push')], default='email', max_length=10),
        ),
    ]
