# Generated by Django 5.1.15 on 2026-09-13 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_devicetoken'),
    ]

    # These fields and this model are already created by users.0001_initial.
    operations = []
