# Generated by Django 5.1.15 on 2026-09-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appointment_charge_id_appointment_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
