# Generated by Django 5.2.18 on 2026-10-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emaildelivery_channel'),
        ('users', '0004_alter_therapist_card_id'),
    ]

    operations = [
    ]
