# Generated by Django 6.1.1 on 2026-09-24 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tracking.chatconversation'),
        ),
        migrations.AddField(
            model_name='circleconnection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_circle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circleconnection',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empathynudge',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_nudges_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empathynudge',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_nudges_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gratitudeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.mood'),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='moods',
            field=models.ManyToManyField(related_name='check_ins', to='tracking.mood'),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empathynudge',
            name='check_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_nudges', to='tracking.moodcheckin'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='mood_check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='tracking.moodcheckin'),
        ),
        migrations.AddField(
            model_name='moodnotification',
            name='mood_check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.moodcheckin'),
        ),
        migrations.AddField(
            model_name='moodnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tracking.mood'),
        ),
        migrations.AddField(
            model_name='relative',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moodnotification',
            name='relative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='tracking.relative'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='tracking.mood'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tracking.workspace'),
        ),
        migrations.AddField(
            model_name='workspacesupportrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_support_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacesupportrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacesupportrequest',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='tracking.workspace'),
        ),
        migrations.AddConstraint(
            model_name='circleconnection',
            constraint=models.UniqueConstraint(fields=('owner', 'recipient'), name='hearteli_unique_circle'),
        ),
        migrations.AlterUniqueTogether(
            name='gratitudeentry',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('mood', 'notification_type')},
        ),
        migrations.AlterUniqueTogether(
            name='workspacemembership',
            unique_together={('workspace', 'user')},
        ),
    ]
