# Generated by Django 4.2.30 on 2026-09-01 02:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_initial'),
    ]

    # These models and relations are already created by tracking.0001 and 0002.
    operations = []
