# Generated by Django 6.1.1 on 2026-09-24 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('categories', models.JSONField(default=list)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HearteliPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_contexts', models.JSONField(blank=True, default=list)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('nudge_notifications', models.BooleanField(default=True)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('rich_lock_preview', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupportOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('yes', 'Yes'), ('a_little', 'A little'), ('not_yet', 'Not yet'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('private_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistContextGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_notes', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='circleconnection',
            name='may_receive_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empathynudge',
            name='delivery_status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('opened', 'Opened')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='empathynudge',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='context_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='feeling_category',
            field=models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('not_great', 'Not great'), ('struggling', 'Struggling')], max_length=20),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='support_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearteli_check_ins', to='tracking.workspace'),
        ),
        migrations.AddConstraint(
            model_name='empathynudge',
            constraint=models.UniqueConstraint(fields=('sender', 'idempotency_key'), name='hearteli_unique_nudge_retry'),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_consent_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.circleconnection'),
        ),
        migrations.AddField(
            model_name='heartelipreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportoutcome',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportoutcome',
            name='nudge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='tracking.empathynudge'),
        ),
        migrations.AddField(
            model_name='therapistcontextgrant',
            name='check_ins',
            field=models.ManyToManyField(related_name='hearteli_therapy_grants', to='tracking.moodcheckin'),
        ),
        migrations.AddField(
            model_name='therapistcontextgrant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_therapy_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='therapistcontextgrant',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearteli_context_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
