# Generated by Django 5.1.15 on 2026-09-02 01:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_chatconversation_moodcheckin_moodnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # These models and relations are already created by tracking.0001 and 0002.
    operations = []
