# Generated by Django 5.1.15 on 2026-09-13 01:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_workspace_workspacesupportrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # These fields already match tracking.0001_initial and tracking.0002_initial.
    operations = []
