# Generated by Django 5.1.15 on 2026-09-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_chatconversation_therapist_alter_gratitudeentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('therapist', 'Therapist'), ('bot', 'AI Counselor')], max_length=10),
        ),
    ]
