# Generated by Django 5.2.17 on 2026-10-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_nudgemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartelipreferences',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='heartelipreferences',
            name='reminder_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='heartelipreferences',
            name='timezone_name',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
