# Generated by Django 5.1.15 on 2026-09-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_chatmessage_sender'),
    ]

    # This field is already created by tracking.0001_initial.
    operations = []
