# Generated by Django 5.2.17 on 2026-10-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_heartelipreferences_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleconnection',
            name='ask_on_pattern',
            field=models.BooleanField(default=False),
        ),
    ]
