# Generated by Django 5.1.15 on 2026-09-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='workspace_type',
            field=models.CharField(choices=[('family', 'Family'), ('couple', 'Couple'), ('office', 'Office')], default='family', max_length=20),
        ),
    ]
