# Generated by Django 5.1.15 on 2026-09-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_workspace_workspace_type'),
    ]

    # This field is already created by tracking.0001_initial.
    operations = []
