# Generated by Django 5.1.15 on 2026-09-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_workspace_workspace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='subscription_plan',
            field=models.CharField(choices=[('personal', 'Personal'), ('office_20', 'Office $20/month')], default='personal', max_length=20),
        ),
    ]
