# Generated by Django 5.2.18 on 2026-10-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_circleconnection_ask_on_pattern'),
        ('tracking', '0008_workspace_subscription_plan'),
    ]

    operations = [
    ]
